/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DiscoverNewStyle: typeof import('./components/HomeSection/DiscoverNewStyle.vue')['default']
    FeatureService: typeof import('./components/HomeSection/FeatureService.vue')['default']
    Footer: typeof import('./components/Header-Footer/Footer.vue')['default']
    Header: typeof import('./components/Header-Footer/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/HomeSection/HeroSection.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Instagram: typeof import('./components/HomeSection/Instagram.vue')['default']
    KnowUsSection: typeof import('./components/HomeSection/KnowUsSection.vue')['default']
    MarqueeNotification: typeof import('./components/Header-Footer/MarqueeNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollHeader: typeof import('./components/Header-Footer/ScrollHeader.vue')['default']
    SeasonOutfit: typeof import('./components/HomeSection/SeasonOutfit.vue')['default']
    SpecialProducts: typeof import('./components/HomeSection/SpecialProducts.vue')['default']
    UniqueDesign: typeof import('./components/HomeSection/UniqueDesign.vue')['default']
  }
}
