/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/AboutSection/AboutCollectionLeft': RouteRecordInfo<'/AboutSection/AboutCollectionLeft', '/AboutSection/AboutCollectionLeft', Record<never, never>, Record<never, never>>,
    '/AboutSection/AboutCollectionRight': RouteRecordInfo<'/AboutSection/AboutCollectionRight', '/AboutSection/AboutCollectionRight', Record<never, never>, Record<never, never>>,
    '/AboutSection/AboutFirstHalf': RouteRecordInfo<'/AboutSection/AboutFirstHalf', '/AboutSection/AboutFirstHalf', Record<never, never>, Record<never, never>>,
    '/AboutSection/InfoPassionateAbout': RouteRecordInfo<'/AboutSection/InfoPassionateAbout', '/AboutSection/InfoPassionateAbout', Record<never, never>, Record<never, never>>,
    '/AboutSection/Team': RouteRecordInfo<'/AboutSection/Team', '/AboutSection/Team', Record<never, never>, Record<never, never>>,
    '/AboutSection/VideoSection': RouteRecordInfo<'/AboutSection/VideoSection', '/AboutSection/VideoSection', Record<never, never>, Record<never, never>>,
    '/Demo/Counter': RouteRecordInfo<'/Demo/Counter', '/Demo/Counter', Record<never, never>, Record<never, never>>,
    '/Demo/demo': RouteRecordInfo<'/Demo/demo', '/Demo/demo', Record<never, never>, Record<never, never>>,
    '/Pages/404Pages': RouteRecordInfo<'/Pages/404Pages', '/Pages/404Pages', Record<never, never>, Record<never, never>>,
    '/Pages/Faq': RouteRecordInfo<'/Pages/Faq', '/Pages/Faq', Record<never, never>, Record<never, never>>,
  }
}
