/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/AboutSection/AboutCollectionLeft': RouteRecordInfo<'/AboutSection/AboutCollectionLeft', '/AboutSection/AboutCollectionLeft', Record<never, never>, Record<never, never>>,
    '/AboutSection/AboutCollectionRight': RouteRecordInfo<'/AboutSection/AboutCollectionRight', '/AboutSection/AboutCollectionRight', Record<never, never>, Record<never, never>>,
    '/AboutSection/AboutFirstHalf': RouteRecordInfo<'/AboutSection/AboutFirstHalf', '/AboutSection/AboutFirstHalf', Record<never, never>, Record<never, never>>,
    '/AboutSection/InfoPassionateAbout': RouteRecordInfo<'/AboutSection/InfoPassionateAbout', '/AboutSection/InfoPassionateAbout', Record<never, never>, Record<never, never>>,
    '/AboutSection/VideoSection': RouteRecordInfo<'/AboutSection/VideoSection', '/AboutSection/VideoSection', Record<never, never>, Record<never, never>>,
    '/Counter': RouteRecordInfo<'/Counter', '/Counter', Record<never, never>, Record<never, never>>,
    '/demo': RouteRecordInfo<'/demo', '/demo', Record<never, never>, Record<never, never>>,
    '/Faq': RouteRecordInfo<'/Faq', '/Faq', Record<never, never>, Record<never, never>>,
  }
}
